Repository falcosecurity/falco-exporter, pull requests merged in 2022-10, with the labels that each got.

#75 Update Alpine to 3.16
  build/Dockerfile
Labels: kind/bug, dco-signoff: yes, lgtm, approved, size/XS

#77 docs: update docs example
  README.md
Labels: kind/documentation, dco-signoff: yes, lgtm, approved, size/XS, area/examples

#78 update(ci): multiple release ci fixes
  .circleci/config.yml
Labels: kind/bug, size/S, dco-signoff: yes, lgtm, approved

#79 fix(ci): drop i386 build + add timeout to goreleaser.
  .circleci/config.yml
  .goreleaser.yml
Labels: kind/cleanup, dco-signoff: yes, lgtm, approved, size/XS

#80 fix(docker): fixed dockerfile golang version.
  build/Dockerfile
Labels: kind/bug, dco-signoff: yes, lgtm, approved, size/XS
